### ISSUE TITLE
Puzzle Reset Error 

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#105]
Boulder do not reset properly. 

First, follow these steps to reproduce the bug: 
Step 1, adjust the puzzle as the following: 
![image](https://user-images.githubusercontent.com/34659673/41189773-b66b6c86-6bdb-11e8-9886-7e79d4fc2450.png)

Next, reset the puzzle, and then do this sequence: 
![image](https://user-images.githubusercontent.com/34659673/41189783-e0f77558-6bdb-11e8-80cd-8701f284ff59.png)

**Comment by KLD** [comment]
@Q8game93 be sure to push the commit
