### ISSUE TITLE
Revise Gem Wave2

### ISSUE THREAD

**Issue by GeoAlghanim** [ChainedRam/Alebi#110]
The wave idea is awesome but, Trouble dodging all projectile.

**Comment by KLD** [comment]
Gameplay comment: 
- [2nd GeoDude's comment] It's barely possible to dodge all projectiles.  
- The diffeculty is static, expected it to grow by time. 

Technical comment: 
 - Lack of Builders

**Comment by dragim** [comment]
It's good, both moon and I found ways to dodge. Hitbox needs to be fixed
