### ISSUE TITLE
Targeted Motion  

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#31]
We surely need a new type of motion that sets aim at a targeted location (rather than direction). 

A Motion in which it would target a `GameObject `(such as the player). 

The motion would have three **inspector** attributes: 
![image](https://user-images.githubusercontent.com/4420439/37478478-636abc6e-288b-11e8-9bd6-1f83da1978c6.png)

//**name : type** Comment
**Target : GameObject** Where the projectile will surely reach. 
**Speed : float** The speed of projection. 
**Degrees : float** Range(-360, 360) the degrees covered before reaching target. Not sure how to explain. So, here''re couple examples: 

Degree = 90° 
![image](https://user-images.githubusercontent.com/4420439/37479104-e1c0014a-288c-11e8-9828-1717df1ca531.png)

Red line is how the projectile would travel. 

Degree = 180° 
![image](https://user-images.githubusercontent.com/4420439/37479282-56575cce-288d-11e8-945f-b35f3b3051b3.png)

Finally, Degree = -30°
![image](https://user-images.githubusercontent.com/4420439/37479468-cb4efbae-288d-11e8-811c-b659fff22a74.png)

Of course, Zero Degree's is a line.

**Comment by KLD** [comment]
@Monstring What do you think about the idea?

**Comment by KLD** [comment]
There's one minor problem that i wont fix which is: 
At the  end of targeting line, the line doesn't match the target's position. In other words, Mathematically, the line doesn't meet the end point. 

Example: 
![image](https://user-images.githubusercontent.com/4420439/37566690-bf5b2cd6-2acd-11e8-8a07-6dd5de69a0b5.png)

If i disable both object's sprites, i'll look like this: 
![image](https://user-images.githubusercontent.com/4420439/37566695-d5f71220-2acd-11e8-9713-a665e1140d0b.png)

And when zooming in the target 
![image](https://user-images.githubusercontent.com/4420439/37566738-4d67a6e4-2ace-11e8-8849-d361fa3a24c6.png)

Colored line (blue+red) is the arc path. The white is direct line between Projectile & Target. 

So, it's not 100% perfect although this is barely noticeable. I think my math isn't implemented perfectly, and I'm open to discussing equations behind this motion.

**Comment by ChainedRam** [comment]
Missing support negative degree, but it's good enough.

**Comment by ChainedRam** [comment]
Whats the status update on this? @KLD

**Comment by ChainedRam** [comment]
- Motion can build a path to target with an arc based on a given positive degree.
- Supporting negative degrees and being compatible with multi-motions 
- Lack of priority 
- ETA N/a

**Comment by ChainedRam** [comment]
Can I assist  with 'being compatible with multi-motions'? @dragim

**Comment by ChainedRam** [comment]
iS DRAGIM participating

**Comment by ChainedRam** [comment]
Ok, lets meet for [30 minutes]
I'm available [Saturday, Sunday after 7:00PM]

**Comment by ChainedRam** [comment]
Sunday at 8:00
