### ISSUE TITLE
Rework Ahmed's Wave

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#42]
https://docs.google.com/spreadsheets/d/1tFeWOPy9wg39lXM0AAhe-R2ptjaKxv5gSwUd9u0ezsQ/edit#gid=1933431416

**Comment by KLD** [comment]
Whats the status report on this? @Monstring

**Comment by Monstring** [comment]
- no progress has been made
- reworking rave wave first, taking longer than expected as i decided to make it 2 waves
- rough EST is 1 weeks time

**Comment by KLD** [comment]
I'll check in a week (Mar 9, 2018)

**Comment by KLD** [comment]
Whats the status report update on this? @Monstring

**Comment by Monstring** [comment]
Should be finished this week, within 2-3 days. delayed due to weekend trp

**Comment by KLD** [comment]
@Monstring I have an idea that will rework this wave.
may you pass this responsibility for me?

**Comment by KLD** [comment]
Reviewed by KLD & Wahab
