### ISSUE TITLE
Rework Rave Wave

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#43]
https://docs.google.com/spreadsheets/d/1tFeWOPy9wg39lXM0AAhe-R2ptjaKxv5gSwUd9u0ezsQ/edit#gid=1933431416

**Comment by KLD** [comment]
Whats the status report on this? @Monstring

**Comment by Monstring** [comment]
- No progress, did not start yet
- Reworking the whole wave and making it simpler
- Difficulties finding time to work
- Monday 2/4/18

**Comment by KLD** [comment]
I'll ask again on that date.

**Comment by Monstring** [comment]
Talal had 4-5 unique projectiles on the rave wave, so i decided to seperate them into 2 waves instead.
the first wave is complete, second one will be done within 1 day from this comment

**Comment by KLD** [comment]
Reviewed by KLD, and Wahab
