### ISSUE TITLE
Design Monstring Wave

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#44]
https://docs.google.com/spreadsheets/d/1tFeWOPy9wg39lXM0AAhe-R2ptjaKxv5gSwUd9u0ezsQ/edit#gid=1933431416

**Comment by KLD** [comment]
Whats the status report on this? @Monstring

**Comment by Monstring** [comment]
Current progress - What is left - Difficulties/Issues - Estimate time of completion
- Have not thought of an idea yet
- Need to check missing unused projectiles and then think of a wave idea
- Still working on the revamp of rave wave and ahmed wave
- 2 weeks rough EST

**Comment by KLD** [comment]
I'll check in in 2 weeks (Mar 9, 2018)

**Comment by Monstring** [comment]
Design complete

**Comment by ChainedRam** [comment]
Continoues wave is approved by KLD, & Reviewed by Wahab.
