### ISSUE TITLE
Blur Effect Reset Bug

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#46]
Sand Projectile blur effect runs out as soon as another sand projectile is thrown.

**Comment by KLD** [comment]
Fixed on c264c8f 

Sand projectile had the blur effects attached to it's prefab. Which when instantiating, was calling 'Start' causing camera to disable it's blur effect. The component was removed.

**Comment by ChainedRam** [comment]
saw it working. 

- Monstring & KLD
