### ISSUE TITLE
Implement Sequential Puzzle Algorithm for Stage 1  

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#47]
Make a puzzle sequence for stage 1.

**Comment by Q8game93** [comment]
what is the status report @KLD?

**Comment by KLD** [comment]
- **Current:** Individual Puzzle is fully functional. 
- **Next:** Have puzzle ending be a starting point for another puzzle. (link list) 
- **Difficulties:** No difficulties 
- **ETA:** Next Saturday

**Comment by Q8game93** [comment]
Can I support youin the making of the algorithm ?

**Comment by KLD** [comment]
Sure. I'm available Tuesday and Wednesday (anytime)

**Comment by Q8game93** [comment]
Wednesday is good

**Comment by KLD** [comment]
What time?

**Comment by KLD** [comment]
Can be tested in the scene.

**Comment by ChainedRam** [comment]
Reviewed by Dragim, & KLD in puzzle  scene
