### ISSUE TITLE
Replace 'GenerateAt' with Direction dropdown. 

### ISSUE THREAD

**Issue by ChainedRam** [ChainedRam/Alebi#49]
![image](https://user-images.githubusercontent.com/34659673/38037255-1efdd374-32b1-11e8-8f55-1786e95ebfac.png)

**Comment by KLD** [comment]
![image](https://user-images.githubusercontent.com/4420439/38471282-8f73d63e-3b77-11e8-8291-c381c806aa75.png)

**Comment by KLD** [comment]
Accidental close

**Comment by ChainedRam** [comment]
Reviewed by KLD & Wahab
