### ISSUE TITLE
Emotions not appearing when testing dialog builder

### ISSUE THREAD

**Issue by dragim** [ChainedRam/Alebi#55]
I made new files for the stage 1 puzzle dialogs. When I tested it, the emotions didn't appear in the scene. This is the dialog i used
![image](https://user-images.githubusercontent.com/34662172/38326152-b3087852-384d-11e8-81bf-2e7b10258d7c.png)
test and fix pls

**Comment by KLD** [comment]
there was duplicate status box, which was overlaying the emotion for the second speaker.

**Comment by ChainedRam** [comment]
Reviewed by Talal & Moomman
