### ISSUE TITLE
Reusing Projectiles 

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#66]
`QueueInstanceGenerator `attempts to reuse created instances, but currently, projectiles, such as _Coin_, does NOT reset properly making it not green friendly (sad tears). 

~~Workaround, set `MaxSize `to -1. This will make the generator generate without reusing previous instance.~~

**Comment by KLD** [comment]
I want to optimize Waves for May Sprint

**Comment by KLD** [comment]
Line Motions are stacking

**Comment by ChainedRam** [comment]
Sand Wave doesn't reset properly ;;

Reviewed by Yousef, Talal, & Khaled

**Comment by KLD** [comment]
Auto closed by merge

**Comment by ChainedRam** [comment]
Reviewed by Ahmad, Yousef, and Khaled
