### ISSUE TITLE
Revise Gem Wave 

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#69]
I'll have Gem Wave be revised and finalized for April Submission. 

To play the Wave, do the following are steps: 
- Switch to Battle-Mode Branch (or download the Unity Project in that branch: [here](https://github.com/ChainedRam/Alebi/archive/Battle-Mode.zip)
- Open 'Alebi' Unity Project 
- In 'Project' tab, locate folder called "Scenes" then double clock file named : "Battle 1"
![image](https://user-images.githubusercontent.com/4420439/39015432-00f1b7c0-4426-11e8-9580-e8f8fde45d8f.png)
- Play the scene clicking the 'Play' button top center. 
- In the Game screen, you'll see a menu of buttons. Click the one you want to play. 
- After finishing, you have to exit play mode to play again. 

If you have any comments, or suggestions, please let me know to make the Wave better! 

There's a similar thread for Net #67  Sand #68  Wave

Once I finalize wave, i'll close this thread.

**Comment by KLD** [comment]
auto-closed when merged to master.

**Comment by ChainedRam** [comment]
Reviewed by Talal & Khaled
