### ISSUE TITLE
Sandwave : Boss doesn't move.

### ISSUE THREAD

**Issue by Q8game93** [ChainedRam/Alebi#76]
![image](https://user-images.githubusercontent.com/37470767/39267977-21abf4c0-48d7-11e8-96c0-7ee4eb651534.png)
This happens when the wave starts.

**Comment by KLD** [comment]
Issue: Alternative motion was calling copy even though it's null. 
Fix: added null check.

**Comment by KLD** [comment]
auto-closed when merged to master.

**Comment by ChainedRam** [comment]
Confirmed by play by Talal & Khaled
