### ISSUE TITLE
Pooling Projectiles 

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#83]
Create a instance pooler. 

How will this work? 

Have an auto config that goes through all InstanceGenerators and gets the type of genrator prefab, and use a dictionarty to get it's hashcode (or use it's pointer). 

Then, make sure to get hte maximum pooling required from those generators. 

Problem: InstanceGenerator is generic at it's root. 

Start by refactoring InstanceGenerator<T> such that InstanceGenerator in that root. 

Then, get rid of QueueInstanceGenerator. To compensate, InstanceGenerator would have an optional 'InstancePooler' that would manager creating\generating instances. 

I think it's cool. It should work. Many things will break.

**Comment by KLD** [comment]
relates to #66

**Comment by ChainedRam** [comment]
Reviewed Talal & Khaled
