### ISSUE TITLE
Refactor DialogBox Script 

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#85]
Based on conversation with @dragim, Dialog's visual will be updated. But the code also needs updating. 

Currently, Characters are displayed as text. which means we are limited to dealing with a `Text` Component. 

Another way is to create a Font of Game objects where each Character is a game object. This way, we can do effects and many crazy things with dialog. 

The first step to this is to create a 'Letter' which DialogBox uses to display, and have a Dialog have a reference for a 'Font' 

Letters can have special effects when displaying. For example: Clear, Newline, Backspace. and so on.

**Comment by KLD** [comment]
![new](https://user-images.githubusercontent.com/4420439/39406901-e022cb1c-4bc6-11e8-94fd-3a48fbdbfd74.png)

**Comment by ChainedRam** [comment]
Migrated to June as part of #94

**Comment by KLD** [comment]
Auto closed by merge

**Comment by KLD** [comment]
Auto closed by merge

**Comment by ChainedRam** [comment]
Reviewed By Abdulwahab, Yousef, Khaled
