### ISSUE TITLE
UML Class Diagram for Puzzle 

### ISSUE THREAD

**Issue by KLD** [ChainedRam/Alebi#86]
To refactor puzzle script, you fist need a design. One way to achieve that is through design UML Class Diagram. You can google that to learn more.

Here's how it could look like: #85 (You'll find a UML Diagram in the comment section). 

Your task is to try to come up UML class Diagram, it doesn't have to be perfect, you'll make a lot of mistakes, but this is one of the best ways to learn designing.

**Comment by ChainedRam** [comment]
abandoned issue
